### ISSUE TITLE
Comments are stripped on SqlFormatter.formatSql()

### ISSUE THREAD

**Issue by apstndb** [google/zetasql#26]
Comments are stripped on `SqlFormatter.formatSql()`.
Enabling `include_comments` is intended behavior to implement formatter.

**Comment by Matts966** [comment]
This problem seems more fundamental. We can't preserve comments only by changing the `include_comments` to `true` because the parser ignores the `COMMENT` tokens.

Fixing this issue is very difficult if we should have comments in AST, however, if we only should preserve comments, we can use tokens parsed by the lexer.
I implemented this in my repository [here](https://github.com/Matts966/zetasql-formatter) with binary for osx and `.pre-commit-hooks.yaml`. I referred your codes such as `zetasql-sandbox`. Thank you!

@apilloud 
Sorry for mentioning you suddenly.  

It would be very appreciated if I know whether a formatter with comments is already planned internally or a PR is acceptable. I would like to send PR after refactoring my code and testing it if PR is acceptable now. 

In any way, I hope the formatter with comments is implemented in this repository because it is useful for other users of this great project. Thank you.

**Comment by apilloud** [comment]
We have a rewritten version of the formatter that supports comments. There was a discussion about releasing it a few months back, I think we deferred the work because no one requested it. I'll send your request along.

Unfortunately we are still unable to accept PRs on this repository (see https://github.com/google/zetasql/blob/master/CONTRIBUTING.md for the current status on that).

**Comment by ebendutoit** [comment]
@apilloud Could you kindly create another release package (2020.05.xx) with the comments support functionality included?

**Comment by ebendutoit** [comment]
Hi there. 

The latest release of zetaSQL has comments functionality included in the formatter, but in the response they only appear stacked at the bottom of the query. 

For example
```
SELECT
test, --comment1,
test2 --comment 2
```
becomes
```
SELECT 
  test,
  test2;
--comment1
--comment2
```

Can this behaviour be changed to keep the comments in-line?
